collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.09183671
color:
  saturation: 1
  brandStrength: 1
  rhythmicContrast: 0.7781955
  brandColors:
    - '#FFFFFF'
    - '#1B1C21'
    - '#455169'
    - '#93AE7B'
    - '#93735A'
  lightness: 0.7792696
layout_spectrum: 1
name: Ellaria Branwen Gunderson Molnar
